inherit_mode:
  merge:
    - Exclude
AllCops:
  SuggestExtensions: false
  Exclude:
    - 'spec/**/*.rb'
    - 'bin/**/*'
Style/Documentation:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
