AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'spec/**/*.rb'
    - 'bin/**/*'
Style/Documentation:
  Enabled: false
Lint/UriEscapeUnescape:
  Enabled: false
Style/MissingRespondToMissing:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
